# remap prefix from 'C-b' to 'C-a'
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix
bind a send-prefix
set-window-option -g xterm-keys on
# see:
#  - https://www.reddit.com/r/neovim/comments/uanvdw/neovimtmux_color_problem/
#  - https://gist.github.com/andersevenrud/015e61af2fd264371032763d4ed965b6
set -ga terminal-overrides ",xterm-256color:Tc"                                                                         
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm' 
# underscore colours - needs tmux-3.0                                                                                               
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# split panes using '|' and '-'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file 
bind r source-file ~/.tmux.conf \; display "Tmux config reloaded!"

# switch panes using Alt-arrow without prefix
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# switch window using Alt-arrow without prefix
bind -n M-Left select-window -t :- 
bind -n M-Right select-window -t :+ 
# press v in copy-mode to start selection
bind -T copy-mode-vi v send -X begin-selection
# press y in copy-mode to yank the texts
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
# prefix + P to paste the text in tmux buffer
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcoy"

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
setw -g mode-keys vi

# move tmux status bar to the top
set -g status-position top

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'wfxr/tmux-power'
# A set of tmux options, see https://github.com/tmux-plugins/tmux-sensible 
set -g @plugin 'tmux-plugins/tmux-sensible'

# plugin settings
# tmux-power themes: gold, redwine, moon, forest, violet, snow, coral, sky
set -g @tmux_power_theme 'snow'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
