#!/bin/bash

# User defined alias
alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias vf='fd --type f --hidden --exclude .git | fzf-tmux -p --reverse | xargs nvim'
alias ls="eza"
alias ll="ls -lha"
alias c="clear"
alias time="gtime"
alias lg="lazygit"
alias lzd="lazydocker"
alias kcm="kubecm"
alias vrc="$EDITOR $HOME/.zshrc"
alias yz="yazi"
alias mx="mise x"
alias mr="mise r"
alias -- -='cd -'
alias ..='cd ..'
alias tmux-broadcast='read "cmd?Command: "; for pane in $(tmux list-panes -a -F "#{pane_id}"); do tmux send-keys -t "$pane" "$cmd" C-m; done'
alias oc="opencode"

portpid() {
  # Check if the second argument is exactly "-v"
  if [ "$2" = "-v" ]; then
    lsof -iTCP:"$1" -sTCP:LISTEN -n -P
  else
    lsof -iTCP:"$1" -sTCP:LISTEN -n -P -t
  fi
}
